server {
    listen 9999;
    server_name _;

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log error;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # 支持 Vue Router 的 history 模式
        try_files $uri $uri/ /index.html;
    }

    location /50x.html {
        root /usr/share/nginx/html;
    }
}